# Generated by Django 5.2.3 on 2025-06-13 00:57

import names_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamaaa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relay',
            name='quick',
            field=models.SlugField(default=names_generator.generate_name, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='streamgroup',
            name='quick',
            field=models.SlugField(default=names_generator.generate_name, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='streamkey',
            name='quick',
            field=models.SlugField(default=names_generator.generate_name, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='streamuser',
            name='quick',
            field=models.SlugField(default=names_generator.generate_name, editable=False, max_length=100, unique=True),
        ),
    ]
