# Generated by Django 5.2.3 on 2025-06-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamaaa', '0002_alter_relay_quick_alter_streamgroup_quick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamgroup',
            name='handle',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='streamuser',
            name='handle',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
