# Generated by Django 5.2.3 on 2025-06-13 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamaaa', '0003_streamgroup_handle_streamuser_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamgroup',
            name='handle',
            field=models.CharField(default=datetime.datetime(2025, 6, 13, 1, 9, 4, 654365, tzinfo=datetime.timezone.utc), max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='streamuser',
            name='handle',
            field=models.CharField(default=datetime.datetime(2025, 6, 13, 1, 9, 16, 556098, tzinfo=datetime.timezone.utc), max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
