# Generated by Django 5.2.3 on 2025-06-13 01:26

import names_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamaaa', '0004_alter_streamgroup_handle_alter_streamuser_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprelayaccess',
            name='quick',
            field=models.SlugField(default=names_generator.generate_name, editable=False, max_length=100, unique=True),
        ),
    ]
