# Generated by Django 5.2.3 on 2025-06-13 01:45

import names_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamaaa', '0005_alter_grouprelayaccess_quick'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamkey',
            name='key',
            field=models.SlugField(default=names_generator.generate_name, max_length=128, unique=True),
        ),
    ]
