# Generated by Django 5.2.3 on 2025-06-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamaaa', '0006_streamkey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamkey',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
