# Generated by Django 5.2.3 on 2025-07-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamaaa', '0007_streamkey_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprelayaccess',
            name='quick',
            field=models.SlugField(default='HopperInfallibleLumiereRitchieGagarin', editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='relay',
            name='quick',
            field=models.SlugField(default='GatesKellerRideNoetherMahavira', editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='streamgroup',
            name='quick',
            field=models.SlugField(default='DazzlingHungryCondescendingBohrFriendly', editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='streamkey',
            name='key',
            field=models.SlugField(default='DazzlingArdinghelliCrazyNightingaleTuDubinskyVarahamihira', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='streamkey',
            name='quick',
            field=models.SlugField(default='HopefulBenzBabbageRosalindCompassionate', editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='streamuser',
            name='quick',
            field=models.SlugField(default='GreatBorgMestorfDijkstraBabbage', editable=False, max_length=100, unique=True),
        ),
    ]
