# Generated by Django 5.2.3 on 2025-07-30 17:22

import streamaaa.names
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamaaa', '0008_alter_grouprelayaccess_quick_alter_relay_quick_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprelayaccess',
            name='quick',
            field=models.SlugField(default=streamaaa.names.generate_name_f, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='relay',
            name='quick',
            field=models.SlugField(default=streamaaa.names.generate_name_f, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='streamgroup',
            name='quick',
            field=models.SlugField(default=streamaaa.names.generate_name_f, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='streamkey',
            name='key',
            field=models.SlugField(default=streamaaa.names.generate_name_f, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='streamkey',
            name='quick',
            field=models.SlugField(default=streamaaa.names.generate_name_f, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='streamuser',
            name='quick',
            field=models.SlugField(default=streamaaa.names.generate_name_f, editable=False, max_length=100, unique=True),
        ),
    ]
